# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
---
layout: default
title: Memories
---
<h1>Memories</h1>
<ul>
  {% for memory in site.memories %}
    <li>
      <a href="{{ memory.url }}">{{ memory.title }}</a>
    </li>
  {% endfor %}
</ul>
