# ---------------------------------------------------------------------------
# Site settings
# ---------------------------------------------------------------------------

title: Bikram's portfolio
first_name: Bikram
middle_name:
last_name: Dholey
contact_note: >
  Best way to reach me: bikram.dholey.563412@gmail.com
description: >
  Academic portfolio of Bikram Dholey – Assistant Professor of Mathematics at Brainware University,
  Ph.D. Candidate at Jadavpur University. Research in wave propagation, smart materials, and elastodynamics.
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
  Photos from <a href="https://unsplash.com" target="_blank">Unsplash</a>.
keywords: jekyll, jekyll-theme, academic-website, portfolio-website
lang: en
icon: ⚛️

url: ""
baseurl: /al-folio
last_updated: false
back_to_top: true

# ---------------------------------------------------------------------------
# Theme
# ---------------------------------------------------------------------------

repo_theme_light: default
repo_theme_dark: dark
repo_trophies:
  enabled: true
  theme_light: flat
  theme_dark: gitdimmed

# ---------------------------------------------------------------------------
# Layout & Navbar
# ---------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true
search_enabled: true
socials_in_search: true
posts_in_search: true
bib_search: true
max_width: 930px

# ---------------------------------------------------------------------------
# Open Graph & Schema.org
# ---------------------------------------------------------------------------

serve_og_meta: false
serve_schema_org: false
og_image:

# ---------------------------------------------------------------------------
# Analytics
# ---------------------------------------------------------------------------

google_analytics:
cronitor_analytics:
pirsch_analytics:
openpanel_analytics:
google_site_verification:
bing_site_verification:

# ---------------------------------------------------------------------------
# Blog
# ---------------------------------------------------------------------------

blog_name: al-folio
blog_description: a simple whitespace theme for academics
permalink: /blog/:year/:title/
lsi: false
pagination:
  enabled: true
related_blog_posts:
  enabled: true
  max_related: 5

giscus:
  repo:
  repo_id:
  category: Comments
  category_id:
  mapping: title
  strict: 1
  reactions_enabled: 1
  input_position: bottom
  theme: preferred_color_scheme
  emit_metadata: 0
  lang: en

disqus_shortname: al-folio

external_sources:
  - name: medium.com
    rss_url: https://medium.com/@al-folio/feed
  - name: Google Blog
    posts:
      - url: https://blog.google/technology/ai/google-gemini-update-flash-ai-assistant-io-2024/
        published_date: 2024-05-14

# ---------------------------------------------------------------------------
# Newsletter
# ---------------------------------------------------------------------------

newsletter:
  enabled: false
  endpoint:

# ---------------------------------------------------------------------------
# Collections
# ---------------------------------------------------------------------------

collections:
  books:
    output: true
  news:
    defaults:
      layout: post
    output: true
  projects:
    output: true

# ---------------------------------------------------------------------------
# Jekyll settings
# ---------------------------------------------------------------------------

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

include: ["_pages", "_scripts"]
exclude:
  - bin/
  - CONTRIBUTING.md
  - CUSTOMIZE.md
  - Dockerfile
  - docker-compose.yml
  - docker-compose-slim.yml
  - FAQ.md
  - Gemfile
  - Gemfile.lock
  - INSTALL.md
  - LICENSE
  - lighthouse_results/
  - package.json
  - package-lock.json
  - _pages/about_einstein.md
  - purgecss.config.js
  - README.md
  - readme_preview/
  - vendor
keep_files:
  - CNAME
  - .nojekyll

plugins:
  - jekyll-archives-v2
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-imagemagick
  - jekyll-jupyter-notebook
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll-regex-replace
  - jekyll/scholar
  - jekyll-sitemap
  - jekyll-tabs
  - jekyll-terser
  - jekyll-toc
  - jekyll-twitter-plugin
  - jemoji
  - jekyll-assets

sass:
  style: compressed

# ---------------------------------------------------------------------------
# Jekyll Minifier
# ---------------------------------------------------------------------------

jekyll-minifier:
  compress_javascript: false
  exclude: ["robots.txt", "assets/js/search/*.js"]

terser:
  compress:
    drop_console: true

# ---------------------------------------------------------------------------
# Jekyll Archives
# ---------------------------------------------------------------------------

jekyll-archives:
  posts:
    enabled: [year, tags, categories]
    permalinks:
      year: "/blog/:year/"
      tags: "/blog/:type/:name/"
      categories: "/blog/:type/:name/"
  books:
    enabled: [year, tags, categories]

display_tags: ["formatting", "images", "links", "math", "code", "blockquotes"]
display_categories: ["external-services"]

# ---------------------------------------------------------------------------
# Jekyll Scholar
# ---------------------------------------------------------------------------

scholar:
  last_name: [Dholey]
  first_name: [Bikram, B.]
  style: apa
  locale: en
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  bibtex_filters: [latex, smallcaps, superscript]
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_link: Details
  query: "@*"
  group_by: year
  group_order: descending

enable_publication_badges:
  altmetric: true
  dimensions: true
  google_scholar: true
  inspirehep: true

filtered_bibtex_keywords:
  - abbr
  - abstract
  - additional_info
  - altmetric
  - annotation
  - arxiv
  - award
  - award_name
  - bibtex_show
  - blog
  - code
  - google_scholar_id
  - html
  - inspirehep_id
  - pdf
  - poster
  - preview
  - selected
  - slides
  - supp
  - video
  - website

max_author_limit: 3
more_authors_animation_delay: 10
enable_publication_thumbnails: true

# ---------------------------------------------------------------------------
# Jekyll Link Attributes
# ---------------------------------------------------------------------------

external_links:
  enabled: true
  rel: external nofollow noopener
  target: _blank
  exclude:

# ---------------------------------------------------------------------------
# Images & Imagemagick
# ---------------------------------------------------------------------------

imagemagick:
  enabled: true
  widths: [480, 800, 1400]
  input_directories: ["assets/img/"]
  input_formats: [".jpg", ".jpeg", ".png", ".tiff"]
  output_formats:
    webp: "-quality 85"

lazy_loading_images: true

# ---------------------------------------------------------------------------
# Optional Features
# ---------------------------------------------------------------------------

enable_google_analytics: false
enable_cronitor_analytics: false
enable_pirsch_analytics: false
enable_openpanel_analytics: false
enable_google_verification: false
enable_bing_verification: false
enable_masonry: true
enable_math: true
enable_tooltips: false
enable_darkmode: true
enable_navbar_social: false
enable_project_categories: true
enable_medium_zoom: true
enable_progressbar: true
enable_video_embedding: false

# ---------------------------------------------------------------------------
# Assets
# ---------------------------------------------------------------------------

assets:
  sources:
    - img/memories/manali

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      default_img: "/assets/img/Morse2.gif"

# ---------------------------------------------------------------------------
# Third-party libraries
# ---------------------------------------------------------------------------

third_party_libraries:
  download: false
  fontawesome:
    url:
      css: "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
  bootstrap:
    url:
      css: "https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      js: "https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
  jquery:
    url:
      js: "https://code.jquery.com/jquery-3.6.0.min.js"
  mathjax:
    version: "3.2.2"
    url:
      fonts: "https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/output/chtml/fonts/woff-v2/"
      js: "https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/tex-mml-chtml.js"
  masonry:
    version: "4.2.2"
    url:
      js: "https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js"
